export const REGISTER_USER = 'REGISTER_USER'
export const SUCCESSFUL_USER_AUTH = 'SUCCESSFUL_USER_AUTH'
export const FAILED_USER_AUTH = 'FAILED_USER_AUTH'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const ADD_NEW_USER = 'ADD_NEW_USER'
export const REFRESH_USERS = 'REFRESH_USERS'
