export const REGISTER_USER = 'REGISTER_USER'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const SUCCESSFUL_USER_AUTH = 'SUCCESSFUL_USER_AUTH'
export const FAILED_USER_AUTH = 'FAILED_USER_AUTH'
